server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # Promtail gửi log đến Loki tại http://loki:3100.

scrape_configs:
  - job_name: containers
    docker_sd_configs: # Promtail tự động phát hiện các container Docker qua Docker socket
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream